version: '3.8'

services:
  podium:
    container_name: podium
    build: .
    ports:
      - "8000:8000"
    # volumes:
      # - ./settings.toml:/app/settings.toml
      # - ./.secrets.toml:/app/.secrets.toml
    tty: true